version: '3.9'

services:
    messagingservice:
      container_name: "thirumathikart_messaging_service"
      image: "thirumathikart_messaging_service"
      build:
        context: .
        target: ${TARGET}
      ports: 
        - ${SERVER_PORT}:${SERVER_PORT} 
      volumes:
        - .:/app 
 
networks:
  default:
      external:
        name: thirumathikart_network