// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	SendSingleNotificationRPC(ctx context.Context, in *SingleNotificationRequest, opts ...grpc.CallOption) (*SingleNotificationResponse, error)
	SendMultipleNotificationRPC(ctx context.Context, in *MultipleNotificationRequest, opts ...grpc.CallOption) (*MultipleNotificationResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SendSingleNotificationRPC(ctx context.Context, in *SingleNotificationRequest, opts ...grpc.CallOption) (*SingleNotificationResponse, error) {
	out := new(SingleNotificationResponse)
	err := c.cc.Invoke(ctx, "/rpcs.NotificationService/SendSingleNotificationRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendMultipleNotificationRPC(ctx context.Context, in *MultipleNotificationRequest, opts ...grpc.CallOption) (*MultipleNotificationResponse, error) {
	out := new(MultipleNotificationResponse)
	err := c.cc.Invoke(ctx, "/rpcs.NotificationService/SendMultipleNotificationRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	SendSingleNotificationRPC(context.Context, *SingleNotificationRequest) (*SingleNotificationResponse, error)
	SendMultipleNotificationRPC(context.Context, *MultipleNotificationRequest) (*MultipleNotificationResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) SendSingleNotificationRPC(context.Context, *SingleNotificationRequest) (*SingleNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSingleNotificationRPC not implemented")
}
func (UnimplementedNotificationServiceServer) SendMultipleNotificationRPC(context.Context, *MultipleNotificationRequest) (*MultipleNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMultipleNotificationRPC not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_SendSingleNotificationRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendSingleNotificationRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcs.NotificationService/SendSingleNotificationRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendSingleNotificationRPC(ctx, req.(*SingleNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendMultipleNotificationRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultipleNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendMultipleNotificationRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcs.NotificationService/SendMultipleNotificationRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendMultipleNotificationRPC(ctx, req.(*MultipleNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcs.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSingleNotificationRPC",
			Handler:    _NotificationService_SendSingleNotificationRPC_Handler,
		},
		{
			MethodName: "SendMultipleNotificationRPC",
			Handler:    _NotificationService_SendMultipleNotificationRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
